### ISSUE TITLE
Areas without names

### ISSUE THREAD

**Issue by keneanung** [IRE-Mudlet-Mapping/AchaeaCrowdmap#108]
When creating the map explorer, I noticed we have some areas without names. Maybe we should clean them up by either giving them a useful name or removing them.

**Comment by ryanstadther** [comment]
So, we used to have a mudlet bug where if you deleted an area in the achaea crowdmap and then swapped maps from previous version to new version and then used the GOTO command it caused mudlet to crash....I -think- it was fixed if I recall, but I haven't tested it yet.

**Comment by vadi2** [comment]
Let's get that tested, it's not a known issue so would be good to fix should it still exist

**Comment by ryanstadther** [comment]
I found the old issue in mudlet...looks like it was probably fixed?

https://github.com/Mudlet/Mudlet/issues/5224

**Comment by vadi2** [comment]
Yup that one definitely was
